### ISSUE TITLE
add new language

### ISSUE THREAD

**Issue by afattahi54** [michaeldelorenzo/keyword-extractor#32]
How is it possible to add new language ?!

**Comment by NotNotMarshall** [comment]
> How is it possible to add new language ?!

I can see that you are from the Middle East. For your information I have added 2 new languages to this library and they are merged already, Arabic and Persian.
Please update to the latest version.


To use any of these 2 languages just pass "arabic" or "persian" to the language key in options.
Like so:
```
const extraction_result =
keyword_extractor.extract(sentence,{
     ...
    language:"persian",
     ...

});
```

**Comment by jimmylevell** [comment]
Currently I am working on a project where we would like to extract keywords from Czech sentences. Would it be possible to support the Czech language too (https://github.com/stopwords-iso/stopwords-cs)? 

Let me know if I should create a merge request for this. Thanks in advanced and kind regards James
