### ISSUE TITLE
npm audit - High Severity CVE due to underscore.

### ISSUE THREAD

**Issue by vignesh-vimana** [michaeldelorenzo/keyword-extractor#59]
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ underscore                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.12.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keyword-extractor                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keyword-extractor > underscore                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1674                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by hemantham0002** [comment]
Any lead on this issue ???
<img width="468" alt="Screenshot 2021-05-24 at 5 47 43 PM" src="https://user-images.githubusercontent.com/55185765/119346682-2b379780-bcb8-11eb-954e-eaa89b8dc88c.png">

**Comment by chfabbro** [comment]
This might be a simple fix. For the sake of expediency, I suggest you update the dependencies and open a PR for the owner to  approve.

**Comment by hemantham0002** [comment]
@chfabbro If you could look into the previous closed PRs,(#48) One of it says, underscore was removed, If so, when I update the package I still see underscore as it dependencies, could you help me with this.

**Comment by cuilongjin** [comment]
> @chfabbro If you could look into the previous closed PRs,(#48) One of it says, underscore was removed, If so, when I update the package I still see underscore as it dependencies, could you help me with this.

@michaeldelorenzo keyword-extractor in npm  is not update

**Comment by chfabbro** [comment]
@hemantham0002 and @cuilongjin I do not see the underscore package. There are no dependencies at all for normal use--only if you want to develop and make further changes. And even then, underscore is not present.
```
    "devDependencies": {
        "browserify": "^17.0.0",
        "esm": "^3.2.25",
        "mocha": "^8.2.0",
        "should": "^13.2.3"
    },
    "dependencies": {},
```

If you install and run an audit, you will see vulnerabilities, but no mention of underscore and again, only if you install the dev dependencies, which are not required to use it normally.

```
$ npm audit

                       === npm audit security report ===

# Run  npm update elliptic --depth 4  to resolve 2 vulnerabilities

  Moderate        Use of a Broken or Risky Cryptographic Algorithm

  Package         elliptic

  Dependency of   browserify [dev]

  Path            browserify > crypto-browserify > browserify-sign > elliptic

  More info       https://npmjs.com/advisories/1648




  Moderate        Use of a Broken or Risky Cryptographic Algorithm

  Package         elliptic

  Dependency of   browserify [dev]

  Path            browserify > crypto-browserify > create-ecdh > elliptic

  More info       https://npmjs.com/advisories/1648



# Run  npm update y18n --depth 3  to resolve 1 vulnerability

  High            Prototype Pollution

  Package         y18n

  Dependency of   mocha [dev]

  Path            mocha > yargs > y18n

  More info       https://npmjs.com/advisories/1654



found 3 vulnerabilities (2 moderate, 1 high) in 263 scanned packages
  run `npm audit fix` to fix 3 of them.
```

**Comment by cuilongjin** [comment]
> @hemantham0002 and @cuilongjin I do not see the underscore package. There are no dependencies at all for normal use--only if you want to develop and make further changes. And even then, underscore is not present.
> 
> ```
>     "devDependencies": {
>         "browserify": "^17.0.0",
>         "esm": "^3.2.25",
>         "mocha": "^8.2.0",
>         "should": "^13.2.3"
>     },
>     "dependencies": {},
> ```
> 
> If you install and run an audit, you will see vulnerabilities, but no mention of underscore and again, only if you install the dev dependencies, which are not required to use it normally.
> 
> ```
> $ npm audit
> 
>                        === npm audit security report ===
> 
> # Run  npm update elliptic --depth 4  to resolve 2 vulnerabilities
> 
>   Moderate        Use of a Broken or Risky Cryptographic Algorithm
> 
>   Package         elliptic
> 
>   Dependency of   browserify [dev]
> 
>   Path            browserify > crypto-browserify > browserify-sign > elliptic
> 
>   More info       https://npmjs.com/advisories/1648
> 
> 
> 
> 
>   Moderate        Use of a Broken or Risky Cryptographic Algorithm
> 
>   Package         elliptic
> 
>   Dependency of   browserify [dev]
> 
>   Path            browserify > crypto-browserify > create-ecdh > elliptic
> 
>   More info       https://npmjs.com/advisories/1648
> 
> 
> 
> # Run  npm update y18n --depth 3  to resolve 1 vulnerability
> 
>   High            Prototype Pollution
> 
>   Package         y18n
> 
>   Dependency of   mocha [dev]
> 
>   Path            mocha > yargs > y18n
> 
>   More info       https://npmjs.com/advisories/1654
> 
> 
> 
> found 3 vulnerabilities (2 moderate, 1 high) in 263 scanned packages
>   run `npm audit fix` to fix 3 of them.
> ```

yes，the reason is npm package is not update, now is ok, thank you 😄
