### ISSUE TITLE
Improve language selection

### ISSUE THREAD

**Issue by otacke** [michaeldelorenzo/keyword-extractor#80]
It would be great if
- the supported languages were [ISO639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (the current names could remain as a fallback to not break existing code) and if
- the list of supported languages was exposed, so one could query them before running into an error that needs to be caught.

If you accept pull requests, please just holler.

**Comment by michaeldelorenzo** [comment]
@otacke pull requests are welcome.
